# Generated by Django 3.1.2 on 2020-10-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('primaryid', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('mobile', models.IntegerField(max_length=10)),
                ('email_id', models.EmailField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
